//this file is generated by program automatically,don't modify it!
#include <drogon/DrTemplate.h>
class UploadPage:public drogon::DrTemplate<UploadPage>
{
public:
	UploadPage(){};
	virtual ~UploadPage(){};
	virtual std::string genText(const drogon::DrTemplateData &) override;
};
