//this file is generated by program automatically,don't modify it!
#include <drogon/DrTemplate.h>
class FeedbackPage:public drogon::DrTemplate<FeedbackPage>
{
public:
	FeedbackPage(){};
	virtual ~FeedbackPage(){};
	virtual std::string genText(const drogon::DrTemplateData &) override;
};
