//this file is generated by program automatically,don't modify it!
#include <drogon/DrTemplate.h>
class SurveyPage:public drogon::DrTemplate<SurveyPage>
{
public:
	SurveyPage(){};
	virtual ~SurveyPage(){};
	virtual std::string genText(const drogon::DrTemplateData &) override;
};
